name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # triggers on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy static site to GitHub Pages
      uses: peaceiris/actions-fdp-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .   # your index.html is in the root