name: HTML Lint CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install HTMLHint
      run: npm install -g htmlhint

    - name: Lint HTML
      run: htmlhint index.html